<?php
if( function_exists('acf_add_local_field_group') ):

// CUSTOM OPTIONS - MAIN
acf_add_local_field_group(array(
  'key' => 'group_custom_options',
  'title' => 'Custom Option',
  'fields' => array(
    array(
      'key' => 'field_custom_option_headline',
      'label' => 'Custom Option Headline',
      'name' => 'headline',
      'type' => 'text',
      'instructions' => 'Enter a headline for this custom option.',
      'required' => 0,
      'conditional_logic' => '',
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array(
      'key' => 'field_custom_option_description',
      'label' => 'Custom Option Description',
      'name' => 'description',
      'type' => 'wysiwyg',
      'instructions' => 'Enter a description of this custom option.',
      'required' => 0,
      'conditional_logic' => '',
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array(
      'key' => 'field_custom_option_summary',
      'label' => 'Brief Summary',
      'name' => 'summary',
      'type' => 'textarea',
      'rows' => 6,
      'instructions' => 'Enter a brief summary of this custom option.',
      'required' => 0,
      'conditional_logic' => '',
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),


  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'custom_option',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array(
    0 => 'the_content',
    1 => 'excerpt',
    2 => 'discussion',
    3 => 'comments',
    4 => 'featured_image',
  ),
  'active' => true,
  'description' => '',
));

// CUSTOM OPTIONS - SIDE
acf_add_local_field_group(array(
  'key' => 'group_custom_options_side',
  'title' => 'Custom Option Side',
  'fields' => array(
    array(
      'key' => 'field_custom_option_image',
      'label' => 'Custom Option Image',
      'name' => 'image',
      'type' => 'image',
      'instructions' => 'Upload an image for this custom option',
      'required' => 0,
      'conditional_logic' => '',
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'width' => '',
      'height' => '',
      'preview_size' => 'medium',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'custom_option',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'side',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array(
    0 => 'the_content',
    1 => 'excerpt',
    2 => 'discussion',
    3 => 'comments',
    4 => 'featured_image',
  ),
  'active' => true,
  'description' => '',
));

//PRODUCT TYPE RELATIONSHIPS - SIDE
acf_add_local_field_group(array(
	'key' => 'group_product_type_relationships',
	'title' => 'Product Type Relationships',
	'fields' => array(
    array(
      'key' => 'field_product_type_summary',
      'label' => 'Search Summary',
      'name' => 'summary',
      'type' => 'textarea',
      'rows' => 8,
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array(
      'key' => 'field_product_type_series',
      'label' => 'Product Series',
      'name' => 'related_series',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'series',
      ),
      'taxonomy' => '',
      'allow_null' => 1,
      'multiple' => 0,
      'return_format' => 'id',
      'ui' => 1,
    ),
    array(
			'key' => 'field_product_type_related_process',
			'label' => 'Processes',
			'name' => 'related_process',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'process',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
    array(
			'key' => 'field_product_type_datasheet',
			'label' => 'Datasheet',
			'name' => 'related_datasheet',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'datasheet',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
    array(
			'key' => 'field_product_type_lit',
			'label' => 'Literature',
			'name' => 'related_lit',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'video',
        1 => 'webinar',
        2 => 'literature',
        3 => 'case_study',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
    array(
      'key' => 'field_product_type_featured_custom_options',
      'label' => 'Featured Custom Options',
      'name' => 'featured_custom_options',
      'type' => 'post_object',
      'instructions' => 'Displays Featured Custom Options on this Product\'s Page',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => 'custom_option',
      'taxonomy' => '',
      'allow_null' => 1,
      'multiple' => 1,
      'return_format' => 'id',
      'ui' => 1,
    ),
    array(
      'key' => 'field_product_type_custom_options',
      'label' => 'All Custom Options',
      'name' => 'related_custom_options',
      'type' => 'post_object',
      'instructions' => 'Defines filters for All Custom Options',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => 'custom_option',
      'taxonomy' => '',
      'allow_null' => 1,
      'multiple' => 1,
      'return_format' => 'id',
      'ui' => 1,
    ),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product_type',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));

// PRODUCT TYPE CONTENT
acf_add_local_field_group(array(
	'key' => 'group_product_type_content',
	'title' => 'Product Type Content',
	'fields' => array(
    array(
      'key' => 'field_product_type_image',
      'label' => 'Product Image',
      'name' => 'product_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '33',
        'class' => '',
        'id' => '',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'preview_size' => 'large',
      'return_format' => 'object',
      'ui' => 1,
    ),
    array(
      'key' => 'field_product_type_content_group',
      'label' => '',
      'name' => 'product_content_group',
      'type' => 'group',
      'sub_fields' => array(
        array(
          'key' => 'field_product_type_description',
          'label' => 'Product Description',
          'name' => 'product_description',
          'type' => 'textarea',
          'rows' => 10,
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),
        array(
    			'key' => 'field_feature_benefits',
    			'label' => 'Feature Benefits',
    			'name' => 'feature_benefits',
    			'type' => 'repeater',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array(
    				'width' => '',
    				'class' => '',
    				'id' => '',
    			),
    			'collapsed' => '',
    			'min' => 0,
    			'max' => 0,
    			'layout' => 'row',
    			'button_label' => 'Add Feature Benefit',
    			'sub_fields' => array(
    				array(
    					'key' => 'field_feature_benefit_value',
    					'label' => 'Feature Benefit',
    					'name' => 'label',
    					'type' => 'text',
    					'instructions' => '',
    					'required' => 0,
    					'conditional_logic' => 0,
    					'wrapper' => array(
    						'width' => '50',
    						'class' => '',
    						'id' => '',
    					),
    					'default_value' => '',
    					'placeholder' => '',
    					'prepend' => '',
    					'append' => '',
    					'maxlength' => '',
    				),
    			),
    		),
        array(
          'key' => 'field_product_type_custom_option_headline',
          'label' => 'Custom Option Headline',
          'name' => 'custom_option_headline',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),
        array(
          'key' => 'field_product_type_custom_option_text',
          'label' => 'Custom Option Lead In Text',
          'name' => 'custom_option_text',
          'type' => 'textarea',
          'rows' => 8,
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),

        array(
          'key' => 'field_product_type_config_gallery_headline',
          'label' => 'Config Gallery Headline',
          'name' => 'config_gallery_headline',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),
        array(
          'key' => 'field_product_type_config_gallery_text',
          'label' => 'Config Gallery Lead In Text',
          'name' => 'config_gallery_text',
          'type' => 'textarea',
          'rows' => 8,
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),

        array(
          'key' => 'field_product_type_saved_layout',
          'label' => 'Below Content - Saved Layout',
          'name' => 'below_content',
          'type' => 'post_object',
          'allow_null' => 1,
          'post_type' => 'saved_layout',
          'required' => 0,
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),

        array(
          'key' => 'field_product_type_footer_resource_column_left',
          'label' => 'Resource Column - Left',
          'name' => 'resource_col_left',
          'type' => 'group',
          'sub_fields' => array(
              array(
                'key' => 'field_product_type_footer_resource_left',
                'label' => 'Resource Type - Left',
                'name' => 'footer_resource_type_left',
                'type' => 'select',
                'choices' => array(
                  'blog' => 'Blogs',
                  'case_study' => 'Case Studies',
                  'video' => 'Videos',
                  'literature' => 'Brochures, Guides & Handbooks',
                  'cta' => 'Call To Action',
                ),
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array(
                'key' => 'field_product_type_footer_resource_method_left',
                'label' => 'Population Method',
                'name' => 'footer_resource_method_left',
                'type' => 'select',
                'choices' => array(
                  'manual' => 'Manual',
                  'most-recent' => 'Most Recent',
                ),
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_product_type_footer_resource_left',
                      'operator' => '!=',
                      'value' => 'cta',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array(
                'key' => 'field_product_type_footer_resource_blog_repeater_left',
                'label' => 'Add Blog Posts',
                'name' => 'footer_blog_repeater_left',
                'type' => 'repeater',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
        								'key' => 'field_footer_resource_list_left_blog_title',
        								'label' => 'Blog Title',
        								'name' => 'blog_title',
        								'type' => 'text',
        								'instructions' => '',
        								'required' => 0,
        								'conditional_logic' => 0,
        								'wrapper' => array(
        									'width' => '',
        									'class' => '',
        									'id' => '',
        								),
        								'placement' => 'top',
        								'endpoint' => 0,
        						),
                    array(
                        'key' => 'field_footer_resource_list_left_blog_summary',
                        'label' => 'Summary',
                        'name' => 'blog_summary',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                          'width' => '',
                          'class' => '',
                          'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
        						array(
        								'key' => 'field_footer_resource_list_left_blog_link_',
        								'label' => 'Blog URL',
        								'name' => 'blog_link',
        								'type' => 'url',
        								'instructions' => '',
        								'required' => 0,
        								'conditional_logic' => 0,
        								'wrapper' => array(
        									'width' => '',
        									'class' => '',
        									'id' => '',
        								),
        								'placement' => 'top',
        								'endpoint' => 0,
        						),
                ),
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_product_type_footer_resource_left',
                      'operator' => '==',
                      'value' => 'blog',
                    ),
                    array(
                      'field' => 'field_product_type_footer_resource_method_left',
                      'operator' => '==',
                      'value' => 'manual',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),


              array(
                'key' => 'field_product_type_footer_resource_case_study_repeater_left',
                'label' => 'Add Case Studies',
                'name' => 'footer_case_study_repeater_left',
                'type' => 'repeater',
                'layout' => 'block',
                'sub_fields' => array(
        						array(
        								'key' => 'field_footer_resource_list_left_case_study',
        								'label' => 'Choose Case Study',
        								'name' => 'case_study',
        								'type' => 'post_object',
                        'post_type' => 'case_study',
                        'allow_null' => 1,
        								'instructions' => '',
        								'required' => 0,
        								'conditional_logic' => 0,
        								'wrapper' => array(
        									'width' => '',
        									'class' => '',
        									'id' => '',
        								),
        								'placement' => 'top',
        								'endpoint' => 0,
        						),
                ),
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_product_type_footer_resource_left',
                      'operator' => '==',
                      'value' => 'case_study',
                    ),
                    array(
                      'field' => 'field_product_type_footer_resource_method_left',
                      'operator' => '==',
                      'value' => 'manual',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),



              array(
                'key' => 'field_product_type_footer_resource_video_repeater_left',
                'label' => 'Add Videos',
                'name' => 'footer_video_repeater_left',
                'type' => 'repeater',
                'layout' => 'block',
                'sub_fields' => array(
        						array(
        								'key' => 'field_footer_resource_list_left_video',
        								'label' => 'Choose Video',
        								'name' => 'video',
        								'type' => 'post_object',
                        'allow_null' => 1,
                        'post_type' => 'video',
        								'instructions' => '',
        								'required' => 0,
        								'conditional_logic' => 0,
        								'wrapper' => array(
        									'width' => '',
        									'class' => '',
        									'id' => '',
        								),
        								'placement' => 'top',
        								'endpoint' => 0,
        						),
                ),
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_product_type_footer_resource_left',
                      'operator' => '==',
                      'value' => 'video',
                    ),
                    array(
                      'field' => 'field_product_type_footer_resource_method_left',
                      'operator' => '==',
                      'value' => 'manual',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),





              array(
                'key' => 'field_product_type_footer_resource_literature_repeater_left',
                'label' => 'Add Literature',
                'name' => 'footer_literature_repeater_left',
                'type' => 'repeater',
                'layout' => 'block',
                'sub_fields' => array(
        						array(
        								'key' => 'field_footer_resource_list_left_literature',
        								'label' => 'Choose Literature',
        								'name' => 'literature',
        								'type' => 'post_object',
                        'allow_null' => 1,
                        'post_type' => 'literature',
        								'instructions' => '',
        								'required' => 0,
        								'conditional_logic' => 0,
        								'wrapper' => array(
        									'width' => '',
        									'class' => '',
        									'id' => '',
        								),
        								'placement' => 'top',
        								'endpoint' => 0,
        						),
                ),
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_product_type_footer_resource_left',
                      'operator' => '==',
                      'value' => 'literature',
                    ),
                    array(
                      'field' => 'field_product_type_footer_resource_method_left',
                      'operator' => '==',
                      'value' => 'manual',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),


              array(
                  'key' => 'field_footer_resource_list_left_cta',
                  'label' => 'Literature CTA',
                  'name' => 'literature',
                  'type' => 'post_object',
                  'post_type' => 'literature',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => array(
                    array(
                      array(
                        'field' => 'field_product_type_footer_resource_left',
                        'operator' => '==',
                        'value' => 'cta',
                      ),
                    ),
                  ),
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'allow_null' => 1,
                  'placement' => 'top',
                  'endpoint' => 0,
              ),





          ),
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
        ),

        // array(
        //   'key' => 'field_product_type_footer_resource_right',
        //   'label' => 'Resource Type - Right',
        //   'name' => 'footer_resource_type_right',
        //   'type' => 'select',
        //   'choices' => array(
        //     'blog' => 'Blogs',
        //     'case_study' => 'Case Studies',
        //     'video' => 'Videos',
        //     'literature' => 'Brochures, Guides & Handbooks',
        //     'cta' => 'Call To Action',
        //   ),
        //   'instructions' => '',
        //   'required' => 0,
        //   'conditional_logic' => 0,
        //   'wrapper' => array(
        //     'width' => '50',
        //     'class' => '',
        //     'id' => '',
        //   ),
        // ),
        //
        // array(
        //   'key' => 'field_product_type_footer_resource_method_right',
        //   'label' => 'Population Method - Right',
        //   'name' => 'footer_resource_method_right',
        //   'type' => 'select',
        //   'choices' => array(
        //     'manual' => 'Manual',
        //     'most-recent' => 'Most Recent',
        //   ),
        //   'instructions' => '',
        //   'required' => 0,
        //   'conditional_logic' => 0,
        //   'wrapper' => array(
        //     'width' => '50',
        //     'class' => '',
        //     'id' => '',
        //   ),
        // ),

      ),
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '66',
        'class' => '',
        'id' => '',
      ),
    ),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product_type',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));

// CONFIGURATION RELATIONSHIPS
acf_add_local_field_group(array(
	'key' => 'group_6115810618986',
	'title' => 'Configuration Relationships',
	'fields' => array(
    array(
      'key' => 'field_product_summary',
      'label' => 'Search Summary',
      'name' => 'summary',
      'type' => 'textarea',
      'rows' => 8,
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array(
      'key' => 'field_61159573464576c17',
      'label' => 'Product Series',
      'name' => 'related_series',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'series',
      ),
      'taxonomy' => '',
      'allow_null' => 1,
      'multiple' => 0,
      'return_format' => 'id',
      'ui' => 1,
    ),
    array(
      'key' => 'field_611581b332c17',
      'label' => 'Product Type',
      'name' => 'related_product_type',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array(
        0 => 'product_type',
      ),
      'taxonomy' => '',
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'id',
      'ui' => 1,
    ),
		array(
			'key' => 'field_6115818632c16',
			'label' => 'Industries',
			'name' => 'related_industries',
			'type' => 'post_object',
			'instructions' => '',
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'industry',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_6115815632c15',
			'label' => 'Processes',
			'name' => 'related_process',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'process',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
    array(
			'key' => 'field_9669694946512c15',
			'label' => 'Datasheet',
			'name' => 'related_datasheet',
			'type' => 'post_object',
      'required' => 0,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'datasheet',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
    array(
			'key' => 'field_61123458908946512c15',
			'label' => 'Literature',
			'name' => 'related_lit',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
      'post_type' => array(
        0 => 'video',
        1 => 'webinar',
        2 => 'literature',
        3 => 'case_study',
      ),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
    array(
      'key' => 'field_7d89456kh12x39876h5f43285c2',
      'label' => 'Custom Options',
      'name' => 'config_related_custom_options',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => 'custom_option',
      'taxonomy' => '',
      'allow_null' => 1,
      'multiple' => 1,
       'return_format' => 'id',
      'ui' => 1,
    ),

	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'typical_config',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));

// CONFIGURATION CONTENT
acf_add_local_field_group(array(
	'key' => 'group_611561641358764123986',
	'title' => 'Configuration Content',
	'fields' => array(
    array(
      'key' => 'field_product_image',
      'label' => 'Product Image',
      'name' => 'product_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '33',
        'class' => '',
        'id' => '',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'preview_size' => 'large',
      'return_format' => 'object',
      'ui' => 1,
    ),
    array(
      'key' => 'field_product_content_group',
      'label' => '',
      'name' => 'product_content_group',
      'type' => 'group',
      'sub_fields' => array(
        array(
          'key' => 'field_product_description',
          'label' => 'Product Description',
          'name' => 'product_description',
          'type' => 'textarea',
          'rows' => 10,
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),
        array(
    			'key' => 'field_611a805f0ccbd',
    			'label' => 'Custom Attributes',
    			'name' => 'attributes',
    			'type' => 'repeater',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array(
    				'width' => '',
    				'class' => '',
    				'id' => '',
    			),
    			'collapsed' => '',
    			'min' => 0,
    			'max' => 0,
    			'layout' => 'row',
    			'button_label' => 'Add Attribute',
    			'sub_fields' => array(
    				array(
    					'key' => 'field_611a80770ccbe',
    					'label' => 'Attribute Label',
    					'name' => 'label',
    					'type' => 'text',
    					'instructions' => '',
    					'required' => 0,
    					'conditional_logic' => 0,
    					'wrapper' => array(
    						'width' => '50',
    						'class' => '',
    						'id' => '',
    					),
    					'default_value' => '',
    					'placeholder' => '',
    					'prepend' => '',
    					'append' => '',
    					'maxlength' => '',
    				),
    				array(
    					'key' => 'field_611a80840ccbf',
    					'label' => 'Attribute Value',
    					'name' => 'value',
    					'type' => 'text',
    					'instructions' => '',
    					'required' => 0,
    					'conditional_logic' => 0,
    					'wrapper' => array(
    						'width' => '50',
    						'class' => '',
    						'id' => '',
    					),
    					'default_value' => '',
    					'placeholder' => '',
    					'prepend' => '',
    					'append' => '',
    					'maxlength' => '',
    				),
    			),
    		),
        array(
          'key' => 'field_config_custom_option_headline',
          'label' => 'Custom Option Headline',
          'name' => 'custom_option_headline',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),
        array(
          'key' => 'field_config_custom_option_text',
          'label' => 'Custom Option Lead In Text',
          'name' => 'custom_option_text',
          'type' => 'textarea',
          'rows' => 8,
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),

        array(
          'key' => 'field_config_config_gallery_headline',
          'label' => 'Config Gallery Headline',
          'name' => 'config_gallery_headline',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),
        array(
          'key' => 'field_config_config_gallery_text',
          'label' => 'Config Gallery Lead In Text',
          'name' => 'config_gallery_text',
          'type' => 'textarea',
          'rows' => 8,
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
        ),
      ),
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '66',
        'class' => '',
        'id' => '',
      ),
    ),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'typical_config',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));

// RESOURCE REDIRECT
acf_add_local_field_group(array(
	'key' => 'group_60b0edcba0650',
	'title' => 'External Destination',
	'fields' => array(
		array(
			'key' => 'field_60b0edf7f6e18',
			'label' => 'Redirect?',
			'name' => 'redirect',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '10',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_60b0edd2f6e17',
			'label' => 'Destination URL',
			'name' => 'destination_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60b0edf7f6e18',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '90',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'literature',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'case_study',
			),
		),
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'webinar',
      ),
    ),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));


// RESOURCE SIDE
acf_add_local_field_group(array(
	'key' => 'group_611ddatasheet_pdf44ff',
	'title' => 'Datasheet PDF',
	'fields' => array(
    array(
      'key' => 'field_datasheet_file',
      'label' => 'Datasheet PDF',
      'name' => 'datasheet_pdf',
      'type' => 'file',
      'mime_types' => 'pdf',
      'instructions' => 'Upload a PDF',
      'required' => 0,
      'conditional_logic' => '',
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => '',
    ),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'datasheet',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));




// RESOURCE SIDE
acf_add_local_field_group(array(
	'key' => 'group_611d344cc44ff',
	'title' => 'Resource Summary',
	'fields' => array(
    array(
      'key' => 'field_resource_image',
      'label' => 'Resource Image',
      'name' => 'image',
      'type' => 'image',
      'instructions' => 'Upload a 16:9 ratio image for use in grids',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => '',
    ),
    array(
      'key' => 'field_resource_cta_image',
      'label' => 'CTA Cover Image',
      'name' => 'cta_image',
      'instructions' => 'Upload a portrait-orientated rectangle cover image for use in CTAs',
      'type' => 'image',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => '',
    ),
		array(
			'key' => 'field_resource_summary',
			'label' => 'Resource Summary',
			'name' => 'summary',
			'type' => 'textarea',
      'new_lines' => 'br',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
    array(
			'key' => 'field_resource_related_process',
			'label' => 'Related Processes',
			'name' => 'related_process',
			'type' => 'post_object',
      'post_type' => 'process',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
      'allow_null' => 1,
			'default_value' => '',
      'multiple' => 1,

		),
    array(
      'key' => 'field_resource_related_indsutry',
      'label' => 'Related Industries',
      'name' => 'related_industry',
      'type' => 'post_object',
      'allow_null' => 1,
      'post_type' => 'industry',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'multiple' => 1,
    ),
    array(
      'key' => 'field_resource_related_product_type',
      'label' => 'Related Product Types',
      'name' => 'related_product_type',
      'type' => 'post_object',
      'post_type' => 'product_type',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'allow_null' => 1,
      'default_value' => '',
      'multiple' => 1,
    ),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'case_study',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'datasheet',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'literature',
			),
		),
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'video',
      ),
    ),
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'webinar',
      ),
    ),
	),
	'menu_order' => 2,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

//VIDEOS
acf_add_local_field_group(array(
  'key' => 'group_videos_content',
  'title' => 'Resources Field Group',
  'fields' => array(
    array(
      'key' => 'field_youtube_code',
      'label' => 'YouTube Video Code',
      'name' => 'youtube_code',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => '',
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'video',
      ),
    ),
  ),
  'menu_order' => 1,
  'position' => 'side',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array(
    0 => 'the_content',
    1 => 'excerpt',
    2 => 'discussion',
    3 => 'comments',
    4 => 'featured_image',
  ),
  'active' => true,
  'description' => '',
));

// RELATED VIDEOS
acf_add_local_field_group(array(
	'key' => 'group_6110987123478654324ff',
	'title' => 'Related Videos',
	'fields' => array(
    array(
      'key' => 'field_videos_related_video',
      'label' => 'Related Videos',
      'name' => 'related_videos',
      'type' => 'post_object',
      'allow_null' => 1,
      'post_type' => 'video',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'multiple' => 1,
    ),

	),
	'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'video',
      ),
    ),
	),
	'menu_order' => 9,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

// PAGE SIDE
acf_add_local_field_group(array(
  'key' => 'group_page_side_options',
  'title' => 'Search Summary',
  'fields' => array(
    array(
      'key' => 'field_page_summary_image',
      'label' => 'Preview Image',
      'name' => 'image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => '',
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'width' => '',
      'height' => '',
      'preview_size' => 'medium',
    ),
    array(
      'key' => 'field_page_summary',
      'label' => 'Summary',
      'name' => 'summary',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => '',
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'width' => '',
      'height' => '',
      'preview_size' => 'medium',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'industry',
      ),
    ),
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'process',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'side',
  //'style' => '',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array(
    0 => 'the_content',
    1 => 'excerpt',
    2 => 'discussion',
    3 => 'comments',
    4 => 'featured_image',
  ),
  'active' => true,
  'description' => '',
));

//REP FIELDS
acf_add_local_field_group(array(
	'key' => 'group_6165ddf92584a',
	'title' => 'Rep Fields',
	'fields' => array(
		array(
			'key' => 'field_6165dee5ac8e4',
			'label' => 'Logo',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
    array(
      'key' => 'field_66543476456235423450',
      'label' => 'Address Formatted',
      'name' => 'address_formatted',
      'type' => 'wysiwyg',
      'toolbar' => 'basic',
      'media_upload' => 0,
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '33',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'basic',
      'media_upload' => 0,
      'delay' => 0,
    ),
    array(
			'key' => 'field_6165df58b7ce3',
			'label' => 'Biography',
			'name' => 'biography',
      'type' => 'wysiwyg',
      'toolbar' => 'basic',
      'media_upload' => 0,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_6165de1cac8e0',
			'label' => 'Email Address',
			'name' => 'email_address',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6165de60ac8e1',
			'label' => 'Phone',
			'name' => 'phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6165de71ac8e3',
			'label' => 'Website URL',
			'name' => 'website_url',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
    array(
			'key' => 'field_6165de00ac8df',
			'label' => 'ZIP Codes',
			'name' => 'zip_codes',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'representative',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
));


endif;
?>
