<?php
$fields =  array(
	'key' => 'layout_two_col_feature_'.$posttype,
	'name' => 'two_col_feature_'.$posttype,
	'label' => 'Two Column Feature',
	'display' => 'block',
	'sub_fields' => array(
    array(
      'key' => 'field_two_col_feature_image_'.$posttype,
      'label' => 'Hero Image',
      'name' => 'two_col_feature_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '40',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
			'key' => 'field_two_col_feature_content_group_'.$posttype,
			'label' => '',
			'name' => 'two_col_feature_content',
			'type' => 'group',
      'sub_fields' => array(
				array(
					'key' => 'field_two_col_feature_left_right_'.$posttype,
					'label' => 'Content Position',
					'name' => 'two_col_feature_left_right',
					'type' => 'true_false',
					'ui' => 1,
					'ui_on_text' => 'Right',
					'ui_off_text' => 'Left',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_two_col_feature_bg_color_'.$posttype,
					'label' => 'Background Color',
					'name' => 'two_col_feature_bg_color',
					'type' => 'select',
					'choices' => array(
						'dark' => 'Dark',
						'light' => 'Light',
					),
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
        array(
    			'key' => 'field_two_col_feature_headline_light_'.$posttype,
    			'label' => 'Flag Text (Light Text)',
    			'name' => 'two_col_feature_headline_light',
    			'type' => 'text',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array(
    				'width' => '50',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => '',
    			'placeholder' => '',
    			'prepend' => '',
    			'append' => '',
    			'maxlength' => '',
    		),
    		array(
    			'key' => 'field_two_col_feature_headline_bold_'.$posttype,
    			'label' => 'Headline (Bold Text)',
    			'name' => 'two_col_feature_headline_bold',
    			'type' => 'text',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array(
    				'width' => '100',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => '',
    			'placeholder' => '',
    			'prepend' => '',
    			'append' => '',
    			'maxlength' => '',
    		),
    		array(
    			'key' => 'field_two_col_feature_text_'.$posttype,
    			'label' => 'Line text',
    			'name' => 'two_col_feature_text',
    			'type' => 'wysiwyg',
					'rows' => 2,
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array(
    				'width' => '',
    				'class' => 'two_col_feature_editor',
    				'id' => '',
    			),
    			'default_value' => '',
    			'tabs' => 'all',
    			'toolbar' => 'basic',
    			'media_upload' => 0,
    			'delay' => 0,
    		),
    		array(
    			'key' => 'field_two_col_feature_button_text_'.$posttype,
    			'label' => 'Button Text',
    			'name' => 'two_col_feature_button_text',
    			'type' => 'text',
    			'instructions' => 'Enter text to display a button.',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array(
    				'width' => '60',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => '',
    			'tabs' => 'all',
    			'toolbar' => 'full',
    			'media_upload' => 1,
    			'delay' => 1,
    		),
    		array(
    			'key' => 'field_two_col_feature_button_link_'.$posttype,
    			'label' => 'Button Link',
    			'name' => 'two_col_feature_button_link',
    			'type' => 'link',
    			'instructions' => 'Choose a link for the button',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array(
    				'width' => '40',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => '',
    			'tabs' => 'all',
    			'toolbar' => 'full',
    			'media_upload' => 1,
    			'delay' => 1,
    		),
      ),
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'min' => '',
	'max' => '',
);

//return $fields;
?>
