<?php

$fields =  array(
	'key' => 'layout_sidebar_cta_'.$posttype,
	'name' => 'sidebar_cta_'.$posttype,
	'label' => 'Sidebar Resource CTA',
	'display' => 'block',
	'sub_fields' => array(
		array(
			'key' => 'field_sidebar_cta_headline_'.$posttype,
			'label' => 'CTA Headline',
			'name' => 'cta_headline',
			'type' => 'text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_sidebar_cta_resource_object_'.$posttype,
			'label' => 'Choose Resource',
			'name' => 'resource_object',
			'type' => 'post_object',
			'post_type' => array( 'case_study', 'datasheet', 'literature', 'video', 'webinar' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_sidebar_cta_padding_top_'.$posttype,
			'label' => 'Padding Top',
			'name' => 'sidebar_cta_padding_top',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => 0,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_sidebar_cta_padding_bot_'.$posttype,
			'label' => 'Padding Bottom',
			'name' => 'sidebar_cta_padding_bot',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => 0,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'min' => '',
	'max' => '',
);

 ?>
