<?php
$fields =  array(
	'key' => 'layout_call_to_action_'.$posttype,
	'name' => 'call_to_action_'.$posttype,
	'label' => 'Call To Action',
	'display' => 'block',
	'sub_fields' => array(
			array(
					'key' => 'field_call_to_action_image_'.$posttype,
					'label' => 'Background Image',
					'name' => 'call_to_action_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
      array(
          'key' => 'field_call_to_action_content_'.$posttype,
          'label' => 'CTA Content',
          'name' => 'call_to_action_content',
          'type' => 'group',
          'sub_fields' => array(
            array(
      					'key' => 'field_call_to_action_headline_'.$posttype,
      					'label' => 'Headline Text',
      					'name' => 'call_to_action_headline',
      					'type' => 'text',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      					'placement' => 'top',
      					'endpoint' => 0,
      			),
            array(
      					'key' => 'field_call_to_action_text_'.$posttype,
      					'label' => 'Line Text',
      					'name' => 'call_to_action_text',
      					'type' => 'text',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array(
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      					'placement' => 'top',
      					'endpoint' => 0,
      			),
            array(
                'key' => 'field_call_to_action_button_text_'.$posttype,
                'label' => 'Button Text',
                'name' => 'call_to_action_button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_call_to_action_button_link_'.$posttype,
                'label' => 'Button Link',
                'name' => 'call_to_action_button_link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
						array(
								'key' => 'field_call_to_action_content_style_'.$posttype,
								'label' => 'CTA Content Style',
								'name' => 'call_to_action_style',
								'type' => 'select',
								'choices' => array(
									'dark' => 'Dark Content',
									'light' => 'Light Content',
								),
								'default_value' => 'dark',
								'return_format' => 'array',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
						),

          ),
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '66',
            'class' => '',
            'id' => '',
          ),
          'placement' => 'top',
          'endpoint' => 0,
      ),

  ),
	'min' => '',
	'max' => '',
);

?>
