<?php

$fields =  array(
	'key' => 'layout_saved_content_'.$posttype,
	'name' => 'saved_content_'.$posttype,
	'label' => 'Saved Layout',
	'display' => 'block',
	'sub_fields' => array(
		array(
			'key' => 'field_saved_content_'.$posttype,
			'label' => 'Saved Layout',
			'name' => 'saved_content_object',
			'type' => 'post_object',
			'post_type' => 'saved_layout',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_saved_content_padding_top_'.$posttype,
			'label' => 'Padding Top',
			'name' => 'saved_content_padding_top',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => 0,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_saved_content_padding_bot_'.$posttype,
			'label' => 'Padding Bottom',
			'name' => 'saved_content_padding_bot',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => 0,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'min' => '',
	'max' => '',
);

 ?>
