<?php
$fields =  array(
	'key' => 'layout_resource_list_'.$posttype,
	'name' => 'resource_list_'.$posttype,
	'label' => 'Resource List',
	'display' => 'block',
	'sub_fields' => array(
      array(
          'key' => 'field_resource_list_title_'.$posttype,
          'label' => 'List Title',
          'name' => 'resource_list_title',
          'type' => 'text',
          'default_value' => '',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '66',
            'class' => '',
            'id' => '',
          ),
          'placement' => 'top',
          'endpoint' => 0,
      ),
			array(
					'key' => 'field_resource_list_method_'.$posttype,
					'label' => 'Method',
					'name' => 'resource_list_method',
					'type' => 'select',
          'choices' => array(
						'most-recent' => 'Show Most Recent',
						'by-topic' => 'By Related Topic',
            'manual' => 'Manually Select',
          ),
          'default_value' => 'blog',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_resource_list_'.$posttype,
					'label' => 'Number of blogs to display',
					'name' => 'resource_list_number',
					'type' => 'select',
          'choices' => array(
            '3' => '3',
            '-1' => 'All',
          ),
          'default_value' => '3',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_resource_list_method_'.$posttype,
								'operator' => '==',
								'value' => 'most-recent',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
      array(
					'key' => 'field_resource_list_post_type_'.$posttype,
					'label' => 'Resource Type',
					'name' => 'resource_list_post_type',
					'type' => 'select',
	        'choices' => array(
	          'blog' => 'Blog',
	          'case_study' => 'Case Study',
						'literature' => 'Literature',
						'webinar' => 'Webinar',
	          'video' => 'Video',
	        ),
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_resource_list_blog_repeater_'.$posttype,
					'label' => 'Add Blog Posts',
					'name' => 'resource_list_blog_repeater',
					'type' => 'repeater',
					'layout' => 'block',
	        'sub_fields' => array(
						array(
								'key' => 'field_resource_list_blog_title_'.$posttype,
								'label' => '',
								'name' => 'resource_list_blog_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
						),
						array(
								'key' => 'field_resource_list_blog_link_'.$posttype,
								'label' => '',
								'name' => 'resource_list_blog_link',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
						),
					),
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_resource_list_post_type_'.$posttype,
								'operator' => '==',
								'value' => 'blog',
							),
							array(
								'field' => 'field_resource_list_method_'.$posttype,
								'operator' => '==',
								'value' => 'manual',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_resource_list_white_paper_repeater_'.$posttype,
					'label' => 'Add White Papers',
					'name' => 'resource_list_white_paper_repeater',
					'type' => 'repeater',
	        'sub_fields' => array(
						array(
								'key' => 'field_resource_list_white_paper_object_'.$posttype,
								'label' => '',
								'name' => 'resource_list_white_paper_object',
								'type' => 'post_object',
				        'post_type' => 'white-paper',
				        'default_value' => 'blog',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
						),
					),
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_resource_list_post_type_'.$posttype,
								'operator' => '==',
								'value' => 'white-paper',
							),
							array(
								'field' => 'field_resource_list_method_'.$posttype,
								'operator' => '==',
								'value' => 'manual',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_resource_list_case_study_repeater_'.$posttype,
					'label' => 'Add Case Studies',
					'name' => 'resource_list_case_study_repeater',
					'type' => 'repeater',
	        'sub_fields' => array(
						array(
								'key' => 'field_resource_list_case_study_object_'.$posttype,
								'label' => '',
								'name' => 'resource_list_case_study_object',
								'type' => 'post_object',
				        'post_type' => 'case-study',
				        'default_value' => 'blog',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
						),
					),
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_resource_list_post_type_'.$posttype,
								'operator' => '==',
								'value' => 'case-study',
							),
							array(
								'field' => 'field_resource_list_method_'.$posttype,
								'operator' => '==',
								'value' => 'manual',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_resource_list_video_repeater_'.$posttype,
					'label' => 'Add Videos',
					'name' => 'resource_list_video_repeater',
					'type' => 'repeater',
	        'sub_fields' => array(
						array(
								'key' => 'field_resource_list_video_object_'.$posttype,
								'label' => '',
								'name' => 'resource_list_video_object',
								'type' => 'post_object',
				        'post_type' => 'video',
				        'default_value' => 'blog',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
						),
					),
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_resource_list_post_type_'.$posttype,
								'operator' => '==',
								'value' => 'video',
							),
							array(
								'field' => 'field_resource_list_method_'.$posttype,
								'operator' => '==',
								'value' => 'manual',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_resource_list_related_process_'.$posttype,
					'label' => 'Related Process',
					'name' => 'resource_list_related_process',
					'type' => 'post_object',
					'return_format' => 'id',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_resource_list_method_'.$posttype,
								'operator' => '==',
								'value' => 'by-topic',
							),
							array(
								'field' => 'field_resource_list_post_type_'.$posttype,
								'operator' => '!=',
								'value' => 'blog',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_resource_list_related_industry_'.$posttype,
					'label' => 'Related Industry',
					'name' => 'resource_list_related_industry',
					'type' => 'post_object',
					'return_format' => 'id',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_resource_list_method_'.$posttype,
								'operator' => '==',
								'value' => 'by-topic',
							),
							array(
								'field' => 'field_resource_list_post_type_'.$posttype,
								'operator' => '!=',
								'value' => 'blog',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),

			array(
					'key' => 'field_resource_list_blog_topic_message_'.$posttype,
					'label' => 'Notice:',
					'name' => 'blog_topic_message',
					'type' => 'html',
					'return_format' => 'id',
					'instructions' => 'By-Topic functionality is not available for Blog Posts. Use "Show Most Recent" or  ',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_resource_list_method_'.$posttype,
								'operator' => '==',
								'value' => 'by-topic',
							),
							array(
								'field' => 'field_resource_list_post_type_'.$posttype,
								'operator' => '==',
								'value' => 'blog',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),

			array(
				'key' => 'field_resource_list_padding_top_'.$posttype,
				'label' => 'Padding Top',
				'name' => 'resource_list_padding_top',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					0 => '0',
					1 => '1',
					2 => '2',
					3 => '3',
					4 => '4',
					5 => '5',
				),
				'default_value' => array(
					0 => 0,
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'resource_list_padding_bot_'.$posttype,
				'label' => 'Padding Bottom',
				'name' => 'resource_list_padding_bot',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					0 => '0',
					1 => '1',
					2 => '2',
					3 => '3',
					4 => '4',
					5 => '5',
				),
				'default_value' => array(
					0 => 0,
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
  ),
	'min' => '',
	'max' => '',
);





?>
