<?php
$fields =  array(
	'key' => 'layout_general_grid_'.$posttype,
	'name' => 'general_grid_'.$posttype,
	'label' => 'General Grid',
	'display' => 'block',
	'sub_fields' => array(
		array(
				'key' => 'field_general_grid_images_tab_'.$posttype,
				'label' => 'Tiles',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
		),
		array(
			'key' => 'field_general_grid_columns_'.$posttype,
			'label' => 'Layout',
			'name' => 'number_of_columns',
			'type' => 'radio',
			'layout' => 'horizontal',
			'choices' => array(
				'2' => '2 Column Grid',
				'3' => '3 Column Grid',
			),
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
    array(
			'key' => 'field_general_grid_content_group_'.$posttype,
			'label' => '',
			'name' => 'general_grid_repeater',
			'type' => 'repeater',
      'min' => '1',
      'button_label' => '+ Add Tile',
      'layout' => 'block',
      'sub_fields' => array(
        array(
          'key' => 'field_general_grid_image_'.$posttype,
          'label' => 'Image',
          'name' => 'image',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '33',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
				array(
					'key' => 'field_general_grid_group_'.$posttype,
					'label' => '',
					'name' => 'tile_group',
					'type' => 'group',
					'sub_fields' => array(
						array(
							'key' => 'field_general_grid_headline_'.$posttype,
							'label' => 'Tile Headline',
							'name' => 'tile_headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
		          'key' => 'field_general_grid_caption_'.$posttype,
		          'label' => 'Tile Text',
		          'name' => 'tile_text',
		          'type' => 'textarea',
							'rows' => '4',
		          'instructions' => '',
		          'required' => 0,
		          'conditional_logic' => 0,
		          'wrapper' => array(
		            'width' => '',
		            'class' => '',
		            'id' => '',
		          ),
		          'default_value' => '',
		          'placeholder' => '',
		          'prepend' => '',
		          'append' => '',
		          'maxlength' => '',
		        ),
		        array(
		          'key' => 'field_general_grid_button_link_'.$posttype,
		          'label' => 'Button Link',
		          'name' => 'button_link',
		          'type' => 'link',
		          'instructions' => '',
		          'required' => 0,
		          'conditional_logic' => 0,
		          'wrapper' => array(
		            'width' => '50',
		            'class' => '',
		            'id' => '',
		          ),
		          'default_value' => '',
		          'placeholder' => '',
		          'prepend' => '',
		          'append' => '',
		          'maxlength' => '',
		        ),
		        array(
		          'key' => 'field_general_grid_button_text_'.$posttype,
		          'label' => 'Button Text',
		          'name' => 'button_text',
		          'type' => 'text',
		          'instructions' => '',
		          'required' => 0,
		          'conditional_logic' => 0,
		          'wrapper' => array(
		            'width' => '50',
		            'class' => '',
		            'id' => '',
		          ),
		          'default_value' => '',
		          'placeholder' => '',
		          'prepend' => '',
		          'append' => '',
		          'maxlength' => '',
		        ),
					),
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '66',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
      ),
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
				'key' => 'field_general_grid_padding_tab_'.$posttype,
				'label' => 'Padding',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
		),

		array(
			'key' => 'field_general_grid_padding_top_'.$posttype,
			'label' => 'Padding Top',
			'name' => 'general_grid_padding_top',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => array(
				0 => 1,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_general_grid_padding_bot_'.$posttype,
			'label' => 'Padding Bottom',
			'name' => 'general_grid_padding_bot',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => array(
				0 => 1,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),


	),
	'min' => '',
	'max' => '',
);

?>
