<?php
$fields =  array(
	'key' => 'layout_summary_'.$posttype,
	'name' => 'summary_'.$posttype,
	'label' => 'Page Summary',
	'display' => 'block',
	'sub_fields' => array(
			array(
					'key' => 'field_sumary_image_'.$posttype,
					'label' => 'Summary Image',
					'name' => 'summary_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
			array(
					'key' => 'field_sumary_text_'.$posttype,
					'label' => 'Primary Summary Text',
					'name' => 'primary_summary_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
			),
      array(
				'key' => 'field_custom_sumary_repeater_'.$posttype,
				'label' => 'Add Custom Summaries',
				'name' => 'custom_summary_repeater',
				'type' => 'repeater',
        'min' => 0,
				'button_label' => '+ Add Custom Summary',
				'sub_fields' => array(
          array(
						'key' => 'field_custom_summary_page_'.$posttype,
						'label' => 'Choose Page for Custom Summary',
						'name' => 'custom_summary_page',
						'type' => 'post_object',
						'return_format' => 'id',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => '',
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'width' => '',
						'height' => '',
					),
					array(
						'key' => 'field_value_calculator_question_'.$posttype,
						'label' => 'Custom Sumary',
						'name' => 'custom_summary',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => '',
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'width' => '',
						'height' => '',
					),
				),
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'layout' => 'block',
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
  ),
	'min' => '',
	'max' => '',
);

?>
