<?php
$fields =  array(
	'key' => 'layout_image_gallery_'.$posttype,
	'name' => 'image_gallery_'.$posttype,
	'label' => 'Image Gallery with Captions',
	'display' => 'block',
	'sub_fields' => array(
		array(
				'key' => 'field_image_gallery_images_tab_'.$posttype,
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
		),
    array(
			'key' => 'field_image_gallery_content_group_'.$posttype,
			'label' => '',
			'name' => 'image_gallery_repeater',
			'type' => 'repeater',
      'min' => '1',
      'max' => '4',
      'button_label' => '+ Add Image',
      'layout' => 'block',
      'sub_fields' => array(
				array(
					'key' => 'field_image_gallery_headline_'.$posttype,
					'label' => 'Image Headline',
					'name' => 'image_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
        array(
          'key' => 'field_image_gallery_image_'.$posttype,
          'label' => 'Image',
          'name' => 'image',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '30',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_image_gallery_caption_'.$posttype,
          'label' => 'Image Caption',
          'name' => 'image_caption',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),
        array(
          'key' => 'field_image_gallery_popup_'.$posttype,
          'label' => 'Image Pop-Up',
          'name' => 'image_popup',
          'type' => 'true_false',
          'ui' => '1',
          'ui_on_text' => 'On',
    			'ui_off_text' => 'Off',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '20',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
        ),

      ),
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
				'key' => 'field_image_gallery_padding_tab_'.$posttype,
				'label' => 'Padding',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
		),

		array(
			'key' => 'field_image_gallery_padding_top_'.$posttype,
			'label' => 'Padding Top',
			'name' => 'image_gallery_padding_top',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => array(
				0 => 1,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_image_gallery_padding_bot_'.$posttype,
			'label' => 'Padding Bottom',
			'name' => 'image_gallery_padding_bot',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => '0',
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
			),
			'default_value' => array(
				0 => 1,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),


	),
	'min' => '',
	'max' => '',
);

?>
